name: Nightly CI

on:
  push:
   branches:
    - nightly

defaults:
  run:
    shell: bash

jobs:
  build_nomaps:
    runs-on: self-hosted
    outputs:
      versionCode: ${{ steps.versioncode.outputs.versionCode }}
      versionName: ${{ steps.versionname.outputs.versionName }}
    steps:
      - uses: actions/checkout@v6
      - name: Get versionCode
        id: versioncode
        run: echo "versionCode=$(grep -E '^\s+versionCode\s*=' app/build.gradle.kts | awk '{ print $3 }' | head -n 1)" >> $GITHUB_OUTPUT
      - name: Get versionName
        id: versionname
        run: echo "versionName=$(grep -E '^\s+versionName\s*=' app/build.gradle.kts | head -1 | awk -F\" '{ print $2 }')" >> $GITHUB_OUTPUT
      - name: Strip internet permission
        run: chmod +x ./strip_permission.sh && ./strip_permission.sh
      - name: Disable maps
        run: echo "INCLUDE_MAPS=false" >> ./app.properties
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 21
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'release_key.jks'
          fileDir: 'app/'
          encodedString: ${{ secrets.SIGNING_KEY }}
      - name: Build Release APK
        run: >-
          ./gradlew
          :app:assembleArm64-v8aNoMLRelease
          :app:assembleArmeabi-v7aNoMLRelease
          :app:assembleX86_64NoMLRelease
          :app:assembleX86NoMLRelease
          :app:assembleUniversalNoMLRelease
        env: 
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      - uses: actions/upload-artifact@v5
        with:
          name: ReFra Release (No Maps)
          path: app/build/outputs/apk-renamed/**/*.apk 

  build_nomaps_withml:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Strip internet permission
        run: chmod +x ./strip_permission.sh && ./strip_permission.sh
      - name: Disable maps
        run: echo "INCLUDE_MAPS=false" >> ./app.properties
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 21
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'release_key.jks'
          fileDir: 'app/'
          encodedString: ${{ secrets.SIGNING_KEY }}
      - name: Build Release APK
        run: >-
          ./gradlew
          :app:assembleArm64-v8aWithMLRelease
          :app:assembleArmeabi-v7aWithMLRelease
          :app:assembleX86_64WithMLRelease
          :app:assembleX86WithMLRelease
          :app:assembleUniversalWithMLRelease
        env: 
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      - uses: actions/upload-artifact@v5
        with:
          name: ReFra Release (No Maps, WithML)
          path: app/build/outputs/apk-renamed/**/*.apk

  build_maps:
    runs-on: self-hosted
    outputs:
      versionCode: ${{ steps.versioncode.outputs.versionCode }}
      versionName: ${{ steps.versionname.outputs.versionName }}
    steps:
      - uses: actions/checkout@v6
      - name: Get versionCode
        id: versioncode
        run: echo "versionCode=$(grep -E '^\s+versionCode\s*=' app/build.gradle.kts | awk '{ print $3 }' | head -n 1)" >> $GITHUB_OUTPUT
      - name: Get versionName
        id: versionname
        run: echo "versionName=$(grep -E '^\s+versionName\s*=' app/build.gradle.kts | head -1 | awk -F\" '{ print $2 }')" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 21
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'release_key.jks'
          fileDir: 'app/'
          encodedString: ${{ secrets.SIGNING_KEY }}
      - name: Build Release APK
        run: >-
          ./gradlew
          :app:assembleArm64-v8aNoMLRelease
          :app:assembleArmeabi-v7aNoMLRelease
          :app:assembleX86_64NoMLRelease
          :app:assembleX86NoMLRelease
          :app:assembleUniversalNoMLRelease
        env: 
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      - uses: actions/upload-artifact@v5
        with:
          name: ReFra Release (Maps)
          path: app/build/outputs/apk-renamed/**/*.apk

  release:
    needs: [build_nomaps, build_nomaps_withml, build_maps]
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: ReFra Release (No Maps)
      - uses: actions/download-artifact@v5
        with:
          name: ReFra Release (Maps)
      - uses: actions/download-artifact@v5
        with:
          name: ReFra Release (No Maps, WithML)
      - name: Generate SHA256
        run: echo "### Checksums" >> ${{ needs.build_maps.outputs.versionName }}-${{ needs.build_maps.outputs.versionCode }}-nightly-changelog.txt && find . -name "ReFra-*.apk" -type f -print0 | sort -z | xargs -r0 sha256sum | awk '{gsub(".*/", "", $2); print "**"$2"**:", "`"$1"`"} ' >> ${{ needs.build_maps.outputs.versionName }}-${{ needs.build_maps.outputs.versionCode }}-nightly-changelog.txt
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ needs.build_maps.outputs.versionName }}-${{ needs.build_maps.outputs.versionCode }} Nightly Release
          body_path: ${{ needs.build_maps.outputs.versionName }}-${{ needs.build_maps.outputs.versionCode }}-nightly-changelog.txt
          prerelease: true
          tag_name: ${{ needs.build_maps.outputs.versionName }}-${{ needs.build_maps.outputs.versionCode }}-nightly
          target_commitish: ${{ github.sha }}
          files: |
            ./**/ReFra-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
